#cloud-config
hostname: vm-ansible
timezone: Europe/Paris

package_update: true
package_upgrade: true
packages:
  - git
  - ansible
  - python3
  - python3-pip

users:
  - default
  - name: ansible
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - git clone https://github.com/mpicherie/infra-lab-iac.git /home/ansible/infra-lab-iac
  - chown -R ansible:ansible /home/ansible/infra-lab-iac
  - echo "✅ Ansible lab is ready!" > /home/ansible/READY.txt
